services:
  backend:
    build: 
      context: ./server/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./server:/workspaces/server:cached
    environment:
      SESSION_COOKIE_KEY: x-john-ahn-session-token
      # 864000 seconds = 10 days
      SESSION_TOKEN_DURATION_SECONDS: 864000
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      # See https://en.wikipedia.org/wiki/Bcrypt for explanation about this parameter.
      BCRYPT_PASSWORD_COST: 12

      APP_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - jwt_secret
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - app-network

  frontend:
    build:
      context: ./client/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - ./client:/workspaces/client:cached
    command: sleep infinity
    networks:
      - app-network

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    secrets:
      - db_password
    networks:
      - app-network

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

networks:
  app-network:

volumes:
  postgres-data:
