services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      SESSION_COOKIE_KEY: x-john-ahn-session-token
      # 864000 seconds = 10 days
      SESSION_TOKEN_DURATION_SECONDS: 864000
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      # See https://en.wikipedia.org/wiki/Bcrypt for explanation about this parameter.
      BCRYPT_PASSWORD_COST: 12

      APP_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - jwt_secret
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    secrets:
      - db_password

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

secrets:
  db_password:
    file: ../secrets/db_password.txt
  jwt_secret:
    file: ../secrets/jwt_secret.txt

volumes:
  postgres-data:
